spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/moneydb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Aakash261204

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

toyandbooklibapp.jwtSecret=BLUEYONDERBELLANDURBENGALURUBLUEYONDERBELLANDURBENGALURUBLUEYONDERBELLANDURBENGALURUBENGALURUBLUEYONDERBELLANDURBENGALURUBENGALURUBLUEYONDERBELLANDURBENGALURU
toyandbooklibapp.jwtExpirationMs=86400000